<html>
<head>

<link rel="StyleSheet" type="text/css" href="first.css">
<title>CONTACT US</title>
</head>
<body bgcolor="#111f77" LINK=RED VLINK=ORANGE ALINK=RED>
<center>
<font color=white><h1>CONTACT US</H1></FONT>
</CENTER>
<hr size=8 color=white noshade>
  <table width="950" border="0" align="center">
    <tr>
      <td height="40";align="center" valign="middle" ><a href="homepage.html" class="login">Home</a></td>
      <td  align="center" valign="middle" ><a href="about.asp" class="login">About </a></td>
       <td  align="center" valign="middle" ><a href="login.asp" class="login">Login</a></td>
      <td align="center" valign="middle"  ><a href="addrec1.html" class="login">Register</a></td>
       <td  align="center" valign="middle"><a href="contact.asp" class="login">Contact Us</a></td>
    </tr>
   </table>
<hr size=2 color=white noshade>
<CENTER>
<font color="white" SIZE=4>
This website has been created by the following, for any further queries you may contact them and for any suggestions please leave your feedback on the following page <a href="feed.asp">Feedback</a>
<ul><li>Sarthak Gupta
<li>Chinmay Agarwal
<li>Prince Bhardwaj</ul>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<CENTER><font color=white><h3>THIS PAGE HAS BEEN VISITED <% RESPONSE.WRITE(NUM) %>  TIMES</CENTER></FONT>
</BODY>
</HTML>