<html>
<head></head>
<body><link rel="StyleSheet" type="text/css" href="first.css">
<center><table width="950" border="0" align="center">
<tr> 
<td width="250" bgcolor="#340">&nbsp;&nbsp;&nbsp;&nbsp;<SPAN STYLE="FONT-FAMILY:COMIC SANS MS ; COLOR:WHITE;VERTICAL-ALIGN:SUPER;FONT-SIZE:30">FEEDBACK...</SPAN></td>
</tr>
</table>
<table width="950" border="0" align="center">
    <tr>
      <td height="40";align="center" valign="middle" ><a href="homepage.html" class="login">Home</a></td>
      <td  align="center" valign="middle" ><a href="about.asp" class="login">About</a></td>
       <td  align="center" valign="middle" ><a href="signin.html" class="login">Login</a></td>
      <td align="center" valign="middle"  ><a href="addrec1.html" class="login">Register</a></td>
       <td  align="center" valign="middle"><a href="contact.asp" class="login">Contact Us</a></td>
    </tr>
   </table>
<FONT COLOR=BLUE>
<HR SIZE=5 NOSHADE color=black>
<BR><BR>
<H1>FEEDBACK FORM</H1><BR>
<FORM NAME=FRM ACTION=FEED1.ASP method=post>
ENTER YOUR NAME &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<INPUT TYPE=TEXT NAME=T1>
<BR>
ENTER YOUR LOGIN ID &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<INPUT TYPE=TEXT NAME=T2><BR>
<p><B>How many stars you want to give for this site</B></p>
<input type="radio" name="g1" value="1">1
<input type="radio" name="g1" value="2">2
<input type="radio" name="g1" value="3">3
<input type="radio" name="g1" value="4">4
<input type="radio" name="g1" value="5">5
<BR>
ENTER YOUR COMMENTS HERE&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<br><br>
<TEXTAREA ROWS=5 COLUMNS=50 NAME=T3>
</TEXTAREA><BR>
<INPUT TYPE=SUBMIT  NAME=B1 VALUE="    SUBMIT HERE    "></FONT>
<center><iframe src="untitled-2.html" width=75% height=50%></center>
</FORM>
</BODY>
</HTML>